Titan/Areas/Warehouse/Models/CartItem.cs
using System.ComponentModel.DataAnnotations;

namespace Titan.Areas.Warehouse.Models
{
    public class CartItem
    {
        [Key]
        public Guid ID { get; set; } = Guid.NewGuid();
        public string ProductBarcode { get; set; }
        public Guid ProductID { get; set; }
        public string ProductName { get; set; }
        public double Cost { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; } = 1;
        public double SubTotalCost { get; set; }
        public double SubTotalPrice { get; set; }
        public DateTime Date { get; set; } = DateTime.Now;
        public Guid ShoppingCartID { get; set; }
    }
}

Titan/Areas/Warehouse/Models/CartItemViewModel.cs
namespace Titan.Areas.Warehouse.Models
{
    public class CartItemViewModel
    {
        public string barcode { get; set; }
        public Guid shoppingCartID { get; set; }
        public int quantity { get; set; } = 1;
        public Guid productID { get; set; }
    }
}

Titan/Areas/Warehouse/Models/Products.cs
namespace Titan.Areas.Warehouse.Models
{
    public class Products
    {
        public Guid ID { get; set; }
        public string Name { get; set; } = string.Empty;
        public double Cost { get; set; }
        public double Price { get; set; }
        public string Barcode { get; set; } = string.Empty;
        public DateTime Date { get; set; } = DateTime.Now;
    }
}

Titan/Areas/Warehouse/Models/ShoppingCart.cs
using System.ComponentModel.DataAnnotations;

namespace Titan.Areas.Warehouse.Models
{
    public class ShoppingCart
    {
        [Key]
        public Guid ID { get; set; }
        public List<CartItem>? CartItem { get; set; }
        public double TotalCosts { get; set; } = 0;
        public double TotalPrices { get; set; } = 0;
        public DateTime Date { get; set; } = DateTime.Now;
        public bool IsSuccessful { get; set; } = false;
        public bool IsActive { get; set; } = true;
    }
}

Titan/Areas/Warehouse/Controllers/CartsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Titan.Areas.Warehouse.APIs.Interfaces;

namespace Titan.Areas.Warehouse.Controllers
{
    [Area("Warehouse")]
    [Authorize(Roles = "Owner,Admin,DataEntry,Cashier")]
    public class CartsController : Controller
    {
        private readonly IShoppingCartInterface shoppingCartInterface;
        private readonly ICartItemInterface cartItemInterface;

        public CartsController(IShoppingCartInterface shoppingCartInterface, ICartItemInterface cartItemInterface)
        {
            this.shoppingCartInterface = shoppingCartInterface;
            this.cartItemInterface = cartItemInterface;
        }
        [Authorize(Roles = "Owner,Admin,Cashier")]
        public async Task<IActionResult> ShoppingCarts()
        {
            return View();
        }

        [Authorize(Roles = "Owner,Admin")]
        public async Task<IActionResult> Sales()
        {
            return View();
        }
    }
}

Titan/Areas/Warehouse/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Titan.Areas.Warehouse.Data.Interfaces;
using Titan.Areas.Warehouse.Models;

namespace Titan.Areas.Warehouse.Controllers
{
    [Area("Warehouse")]
    //[Authorize(Roles = "Owner,Admin,DataEntry")]
    [Authorize(Roles = "Admin,Owner,DataEntry,Cashier")]
    public class ProductsController : Controller
    {
        private readonly IProductInterface productInterface;

        public ProductsController(IProductInterface productInterface)
        {
            this.productInterface = productInterface;
        }
        public async Task<IActionResult> Index()
        {
            var prd = await productInterface.GETALL();
            prd = prd.OrderByDescending(o => o.Date).ToList();
            return View(prd);
        }
    }
}

Titan/Areas/Warehouse/Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Titan.Areas.Warehouse.Controllers
{
    [Area("Warehouse")]
    //[Authorize(Roles = "Owner,Admin,DataEntry")]
    [Authorize(Roles = "Admin,Owner,DataEntry,Investors")]
    public class WarehouseController : Controller
    {
        public IActionResult Dashboard()
        {
            return View();
        }
    }
}

Titan/Areas/Warehouse/Views/Warehouse/Dashboard.cshtml
@{
    ViewData["Title"] = "Warehouse - Dashboard";
}

<div class="row">
    <div class="col-sm-3"> 
        <div class="card" style="width: 18rem;">
            <img src="~/images/Grocary.jpg" class="card-img-top" style="max-height:200px" alt="prduct image">
            <div class="card-body d-grid gap-2 mx-auto">
                <h5 class="card-title">Products</h5>
                    <p class="card-text">There Is About 1500 Products...</p>
                <a asp-area="Warehouse" asp-controller="Products" asp-action="Index" class="btn btn-primary">Go Fetch</a>
            </div>
        </div>
    </div>
    
    <div class="col-sm-3"> 
        <div class="card" style="width: 18rem;">
            <img src="~/images/carts.webp" class="card-img-top" style="max-height:200px" alt="prduct image">
            <div class="card-body d-grid gap-2 mx-auto">
                <h5 class="card-title">Shopping Carts</h5>
                    <p class="card-text">There Is About 1500 Products...</p>
                <a asp-area="Warehouse" asp-controller="Carts" asp-action="ShoppingCarts" class="btn btn-primary">Go Fetch</a>
            </div>
        </div>
    </div>

    <div class="col-sm-3"> 
        <div class="card" style="width: 18rem;">
            <img src="~/images/money.webp" class="card-img-top" style="max-height:200px" alt="prduct image">
            <div class="card-body d-grid gap-2 mx-auto">
                <h5 class="card-title">Sales</h5>
                    <p class="card-text">There Is About 1500 Products...</p>
                <a asp-area="Warehouse" asp-controller="Carts" asp-action="Sales" class="btn btn-primary">Go Fetch</a>
            </div>
        </div>
    </div>
</div>